-- Future SQL template for GET /api/analytics/overview.
--
-- Expected params:
--   %(group_by)s
--   %(period_start)s
--   %(period_end)s
--   %(previous_period_start)s
--   %(previous_year_start)s
--
-- Expected result columns:
--   id
--   label
--   count
--   revenue
--   revenue_mom_pct
--   revenue_yoy_pct
--   fuel_volume
--   fuel_volume_mom_pct
--   fuel_volume_yoy_pct
--   checks
--   checks_mom_pct
--   checks_yoy_pct
--   avg_check
--   avg_check_mom_pct
--   avg_check_yoy_pct
--
-- Replace this placeholder with grouped KPI aggregation by ТМ, РУ or АЗС.
